services:
  - type: web
    name: movie-rental-backend
    runtime: docker
    rootDir: backend
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGIN
        sync: false
      - key: REDIS_URL
        sync: false
